services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    ports:
      - ${TRAEFIK_HTTP_PORT}:80
      - ${TRAEFIK_DASHBOARD_PORT}:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik/static.yml:/traefik.yml:ro
      - ./config/traefik/dynamic.yml:/dynamic.yml:ro
    networks:
      - main-network

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - main-network

  fastapi:
    image: fastapi:latest
    container_name: fastap-test
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_DATABASE: ${POSTGRES_DB}
      PYTHONPATH: /home/appuser/
      SHARED_FOLDER: ${SHARED_FOLDER}
      TESTMODE: True
    volumes:
      - ./data/fastapi/shared:/home/appuser/shared
    entrypoint: /home/appuser/testing-entrypoint.sh
    depends_on:
      - postgres
      - traefik
    networks:
      - main-network

networks:
  main-network:
    driver: bridge
